// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID          int32
	ShortCode   string
	OriginalUrl string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	ClickCount  pgtype.Int4
}
