// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createURL = `-- name: CreateURL :one

INSERT INTO urls (short_code, original_url, expires_at)
VALUES ($1, $2, $3)
RETURNING id, short_code, original_url, created_at, expires_at, click_count
`

type CreateURLParams struct {
	ShortCode   string
	OriginalUrl string
	ExpiresAt   pgtype.Timestamptz
}

// URL Shortener SQL Queries
func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL, arg.ShortCode, arg.OriginalUrl, arg.ExpiresAt)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClickCount,
	)
	return i, err
}

const deleteExpiredURLs = `-- name: DeleteExpiredURLs :exec
DELETE FROM urls
WHERE expires_at IS NOT NULL
AND expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredURLs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredURLs)
	return err
}

const getURLByShortCode = `-- name: GetURLByShortCode :one
SELECT id, short_code, original_url, created_at, expires_at, click_count
FROM urls
WHERE short_code = $1
AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP)
`

func (q *Queries) GetURLByShortCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByShortCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClickCount,
	)
	return i, err
}

const getURLStats = `-- name: GetURLStats :one
SELECT id, short_code, original_url, created_at, expires_at, click_count
FROM urls
WHERE short_code = $1
`

func (q *Queries) GetURLStats(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLStats, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClickCount,
	)
	return i, err
}

const incrementClickCount = `-- name: IncrementClickCount :exec
UPDATE urls
SET click_count = click_count + 1
WHERE short_code = $1
`

func (q *Queries) IncrementClickCount(ctx context.Context, shortCode string) error {
	_, err := q.db.Exec(ctx, incrementClickCount, shortCode)
	return err
}
